name: 🔍 Verify Android Keystore Secrets (Safe Debug)

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for required secrets
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
        run: |
          echo "🔍 Checking for Android keystore secrets..."
          MISSING=0

          if [ -z "$KEYSTORE_BASE64" ]; then
            echo "⚠️  ANDROID_KEYSTORE_BASE64 is MISSING!"
            MISSING=1
          else
            echo "✅ ANDROID_KEYSTORE_BASE64 found (${#KEYSTORE_BASE64} bytes)"
          fi

          if [ -z "$KEYSTORE_PASSWORD" ]; then
            echo "⚠️  ANDROID_KEYSTORE_PASSWORD is MISSING!"
            MISSING=1
          else
            echo "✅ ANDROID_KEYSTORE_PASSWORD found"
          fi

          if [ -z "$KEY_ALIAS" ]; then
            echo "⚠️  ANDROID_KEY_ALIAS is MISSING!"
            MISSING=1
          else
            echo "✅ ANDROID_KEY_ALIAS found"
          fi

          if [ -z "$KEY_ALIAS_PASSWORD" ]; then
            echo "⚠️  ANDROID_KEY_ALIAS_PASSWORD is MISSING!"
            MISSING=1
          else
            echo "✅ ANDROID_KEY_ALIAS_PASSWORD found"
          fi

          if [ "$MISSING" -eq 0 ]; then
            echo "🎉 All Android keystore secrets are available!"
          else
            echo "🚨 One or more secrets are missing!"
            echo "Go to Settings → Secrets and variables → Actions to fix."
            exit 1
          fi
