name: Check Android Keystore Secrets

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          echo "🔍 Checking for Android keystore secrets..."
          echo ""

          check_secret() {
            local name="$1"
            if [ -z "${!name}" ]; then
              echo "⚠️  $name is MISSING!"
            else
              echo "✅  $name is PRESENT"
            fi
          }

          check_secret "ANDROID_KEYSTORE_BASE64"
          check_secret "ANDROID_KEYSTORE_PASSWORD"
          check_secret "ANDROID_KEY_ALIAS"
          check_secret "ANDROID_KEY_ALIAS_PASSWORD"

          echo ""
          echo "🔧 If any are missing, go to:"
          echo "   Settings → Secrets and variables → Actions → New repository secret"
          echo ""
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
